## <u>PYTHON DATA TYPES</u>

    * Text Type     :	str
    * Numeric Types :	int, float, complex
    * Sequence Types:	list, tuple, range
    * Mapping Type  :	dict
    * Set Types     :	set, frozenset
    * Boolean Type  :	bool
    * Binary Types  :	bytes, bytearray, memoryview
    * None Type     :	NoneType

### 1.  RANGE :

    eg : for i in range(5):
            print(i)

    * The range data type in Python represents a sequence of numbers and is commonly used in for loops. 
    * three parameters: start, stop, and step.
    * range objects are iterable, but not indexable or sliceable.
    * 'List' function to convert 'range' object to a list.

### 2.  DICTIONARY :

    eg: phonebook = {"John": 123456789, "Jane": 987654321, "Jim": 111111111}
        print(phonebook)

        phonebook["Tom"] = 222222222 # adding a new key-value pair
        phonebook["John"] = 111111111 # updating a value
        del phonebook["Jane"] # deleting a key-value pair
        print(phonebook)
    
    * unordered collection of key-value pairs, where each key maps to a value.
    * add, update, and delete key-value pairs in a dictionary.
    * keys should be unique and of immutable data type(eg: string, numbers, tuples).

### 3.  MEMORYVIEW :

    eg: b = bytearray(b'abcd')
        mv = memoryview(b)
        print(mv[1]) # outputs 98

    * allows you to access memory of an object without creating a copy of it.
    * read-only and sequence-type object that provides a memory-efficient way to handle bytes-like objects

### 4.  NONETYPE :

    eg: def return_none():
        return None

        result = return_none()
        print(result)
        print(type(result))

    * represents the absence of a value.
    * used to indicate that a variable or function has no value, or that a value is not specified.
    

## <u>FOR/WHILE LOOPS</u>

### FOR LOOP:

    eg: for val in sequence:
         # statement(s)

    * used to run a block of code for a certain number of times. 
    * used to iterate over any sequences such as list, tuple, string, etc.

### LOOP OVER PYTHON LISTS:

    eg: languages = ['Swift', 'Python', 'Go', 'JavaScript']
        for language in languages:
            print(language)

### LOOP WITH PYTHON RANGE:

    eg: values = range(4)
        for i in values:
            print(i)

### LOOP WITH PYTHON ELSE:

    eg: digits = [0, 1, 5]
        for i in digits:
            print(i)
        else:
            print("No items left.")

### <u>WHILE LOOP:</u>

    eg: while condition:
        # body of while loop

    * while loop is used to run a block code until a certain condition is met.

## <u>IF/ELIF/ELIF:</u>

    eg: if condition:
            # Code to be executed if condition is True
        elif condition:
            # Code to be executed if this condition is True
        else:
            # Code to be executed if all previous conditions are False

        x = 5
        if x > 10:
            print("x is greater than 10")
        elif x > 0:
            print("x is positive but less than or equal to 10")
        else:
            print("x is not positive")

## <u>LIST:</u>

    fruits = ['apple', 'banana', 'cherry']

    # Adding an item to the end of a list
    fruits.append('orange')
    print(fruits) # Output: ['apple', 'banana', 'cherry', 'orange']

    # Removing an item from a list
    fruits.remove('banana')
    print(fruits) # Output: ['apple', 'cherry', 'orange']

    # Finding the length of a list
    print(len(fruits)) # Output: 3

    # slicing to extract a portion of the list
    fruits = ['apple', 'banana', 'cherry', 'orange']
    print(fruits[1:3]) # Output: ['banana', 'cherry']

    # modify items in a list
    fruits = ['apple', 'banana', 'cherry']
    fruits[0] = 'orange'
    print(fruits) # Output: ['orange', 'banana', 'cherry']

## <u>TUPLE:</u>

    * A tuple is a collection of items, separated by commas and enclosed in parentheses ().
    * contain items of different data types, including numbers, strings, and other data structures. 
    * tuples are immutable, which means that you cannot change the items in a tuple after it has been created.
    * used as keys in dictionaries, since they are hashable and have a fixed size.
    * tuples are often used for multiple return values from a function. For example:

    def min_max(numbers):
    return min(numbers), max(numbers)

    numbers = [3, 7, 1, 9, 5]
    min_val, max_val = min_max(numbers)
    print(min_val) # Output: 1
    print(max_val) # Output: 9

    * Tuples can also be unpacked directly into variables. For example:

    colors = ('red', 'green', 'blue')
    r, g, b = colors
    print(r) # Output: 'red'
    print(g) # Output: 'green'
    print(b) # Output: 'blue'

## <u>DICTIONARY</u>

    * a dictionary is a collection of key-value pairs, where each key is mapped to a value.
    * unordered and mutable.
    * Dictionaries are implemented as hash tables, which provide constant-time lookups for keys.
    
    # To access a value in a dictionary
    print(my_dict["name"])
        John

    # modify the values
    my_dict["age"] = 31
    print(my_dict)
    {'name': 'John', 'age': 31, 'city': 'New York'}

    # To add a new key-value pair to a dictionary
    my_dict["country"] = "USA"
    print(my_dict)
    {'name': 'John', 'age': 31, 'city': 'New York', 'country': 'USA'}

    # To delete a key-value pair from a dictionary
    del my_dict["age"]
    print(my_dict)
    {'name': 'John', 'city': 'New York', 'country': 'USA'} 

## <u>SET:</u>

    * a set is an unordered collection of unique elements.
    * Sets are mutable
    * unordered collections of unique elements.

    # creating a set
    >>> my_set = {1, 2, 3, 4}
    >>> print(my_set)
    {1, 2, 3, 4}

    # to add elements
    >>> my_set.add(5)
    >>> print(my_set)
    {1, 2, 3, 4, 5}

    # to remove elements
    >>> my_set.remove(3)
    >>> print(my_set)
    {1, 2, 4, 5}

    # to perform union
    >>> set1 = {1, 2, 3}
    >>> set2 = {3, 4, 5}
    >>> union = set1.union(set2)
    >>> print(union)
    {1, 2, 3, 4, 5}

## <u>MAP:</u>

    eg: >>> numbers = [1, 2, 3, 4, 5]
        >>> result = map(lambda x: x**2, numbers)
        >>> print(list(result))
        [1, 4, 9, 16, 25]

    * the map function is used to apply a function to each item in an iterable (such as a list, tuple, set, or dictionary) and   return a new iterable with the results.

## <u>OOP's Concepts:</u>

    Class, Objects, Polymorphism, Encapsulation, Inheritance, Data Abstraction

### Class:

    * A class is a collection of objects. 
    * A class contains the blueprints or the prototype from which the objects are being created. 
    * It is a logical entity that contains some attributes and methods. 

### Objects: 

    * 1. The object is an entity that has a state and behavior associated with it. 
    * 2. It may be any real-world object like a mouse, keyboard, chair, table, pen, etc. 
    * 3. Integers, strings, floating-point numbers, even arrays, and dictionaries, are all objects.

### Inheritance:

    * Inheritance is the capability of one class to derive or inherit the properties from another class. 
    * The class that derives properties is called the derived class or child class and the class from which the properties are being derived is called the base class or parent class.

### Polymorphism: 

    * Polymorphism simply means having many forms. 
    * For example, we need to determine if the given species of birds fly or not, using polymorphism we can do this using a single function.

### Encapsulation:
    
    * It describes the idea of wrapping data and the methods that work on data within one unit. 
    * This puts restrictions on accessing variables and methods directly and can prevent the accidental modification of data.

### Data Abstraction:

    * It hides the unnecessary code details from the user. 
    * Also,  when we do not want to give out sensitive parts of our code implementation and this is where data abstraction came.
    



## <u>How to import a Class from another file in python:</u> 

## using the import command:

    #Code starts here
 
    MyFile.py
    class Square:
    def __init__(self,val):
        self.val=val
    def getVal(self):
        return self.val*self.val
    
    main.py
    from MyFile import Square
    
    newClass = Square(5)
    val = newClass.getVal()
    
    print(val)
    
    #Code ends here

## Import multiple classes from one file using the import command:

    MyFile.py
    class Square:
        def __init__(self,val):
            self.val=val
        def getVal(self):
            return self.val*self.val
    
    
    class Add_Sub:
        def add(self, a, b):
            return a + b
        def sub(self, a, b):
            return a - b
    
    main.py
    import MyFile
    # creating object for Square class
    object1 = MyFile.Square(5)
    print(f"From class Square: {object1.getVal()}")
    # creating object for Add_Sub class
    object2 = MyFile.Add_Sub()
    print(f"From class Add_Sub: Addition {object2.add(2,3)}")
    print(f"From class Add_Sub: Subtraction {object2.sub(2,3)}")
    
    #Code ends here

## Import all classes from one file using the import* command:

    #Code starts here
 
    MyFile.py
    class Square:
    def __init__(self,val):
        self.val=val
    def getVal(self):
        return self.val*self.val
    
    
    class Add_Sub:
    def add(self, a, b):
        return a + b
    def sub(self, a, b):
        return a - b
    
    main.py
    from MyFile import *
    # creating object for Square class
    object1 = Square(5)
    print(f"From class Square: {object1.getVal()}")
    # creating object for Add_Sub class
    object2 = Add_Sub()
    print(f"From class Add_Sub: Addition {object2.add(2,3)}")
    print(f"From class Add_Sub: Addition {object2.sub(2,3)}")
    
    #Code ends here

## Import all classes from another folder in parent directory using import sys command:

    #Code starts here
 
    main.py
    import sys
    sys.path.insert(0,"..")
    from Inner_Project.MyFile import Square
    object = Square(5)
    print(object.getVal())
    
    #Code ends here

## Importing a class dynamically: 

    #Code starts here
    
    module.py
    # class inside the module
    class MyClass:
    def myclass(str):
        print(f"Hello How are you {str} ?")
    
    Dynamic.py
    class Dyclass:
        def __init__(self, module_name, class_name):
    
            module = __import__(module_name) # __import__ method used to getmodule
            my_class = getattr(module, class_name) #getting attribute by getattr() 
            my_class.myclass('Usman')
    
    obj = Dyclass("module", "MyClass")
    
    #Code ends here

## <u>File I/O operations | Creating and removing files/folders:</u>

    os.remove('file_path')	                -Removes the specified file.
    os.unlink('file_path')	                -Removes the specified file. Useful in UNIX environment.
    pathlib.Path("file_path").unlink()	    -Delete the file or symbolic link in the mentioned path
    os.rmdir('empty_dir_path')	            -Removes the empty folder.
    pathlib.Path(empty_dir_path).rmdir()	-Unlink and delete the empty folder.
    shutil.rmtree('dir_path')	            -Delete a directory and the files contained in it.

## <u>Numpy:</u>

    import numpy as np

### Creating Arrays:

    c = np.array([[(1.5,3,4),(4,5,6)],[(2,3,4),(3,4,5)]], dtype = float)

### Initial Placeholders:

    >>> np. zeros((3,4))                    #Create an array of zeros 
    >>> np.ones((2,3,4),dtype=np.int 16)    #Create an array of ones
    >>> d = np.arange(10,25,5)              #Create an array of evenly spaced values (step value ) 
    >>> np.linspace( 0,2,9)                 #Create an array of evenly spaced values (number of samples ) 
    >>> e = np.full((2,2),7)                #Create a constant array 
    >>> f = np.eye(2)                       #Create a 2 X2 identity matrix
    >>> np.random.random((2,2))             #Create an array with random values
    >>> np.empty((3,2))                     #Create an empty array  

### Saving and Loading on Disk:

    >>> np.save('my_array', a)
    >>> np.savez('array.npz', a, b)
    >>> np.load('my_array.npy')

### Saving & Loading Text Files:

    >>> np.loadtxt("myfile.txt") 
    >>> np.genfromtxt("my_file.csv", delimiter=',') 
    >>> np.savetxt("myarray.txt", a, delimiter=" " )

### Inspecting your array:

    >>> a.shape             # Array dimensions
    >>> len(a)              # Length of array
    >>> b.ndim              # Number of array dimensions
    >>> e.size              # Number of array elements
    >>> b.dtype             # Data type of array elements 
    >>> b.dtype.name        # Name of data type 
    >>> b.astype(int)       # Convert an array to a different type

### Data Types:

    >>> np.int64 #Signed 64-bit integer types
    >>> np.float32. #Standard double-precision floating point
    >>> np.complex. #Complex numbers represented by 128 floats
    >>> np.bool  #Boolean type storing TRUE and FALSE values
    >>> np.object #Python object type
    >>> np.string_ #Fixed-length string type
    >>> np.unicode_ #Fixed-length unicode type

### Arithmetic Operations:

    >>> g = a - b. #Subtraction
    array([[-0.5,0. ,0.], [-3. , -3. , -3. ]])
    >>> np.subtract(a,b) #Subtraction
    >>> b + a #Addition 
    array([[ 2.5, 4. , 6.],[5. ,7. ,9. ]])
    >>> np.add(b,a) #Addition 
    >>> a/b #Division 
    array([[0.66666667,1. ,1.],[0.25 ,0.4 ,0.5 ]])
    >>> np.divide(a,b) #Division 
    >>> a * b #Multiplication 
    array([[1.5, 4. ,9.],[ 4. , 10. , 18. ]])
    >>> np.multiply(a,b) #Multiplication 
    >>> np.exp(b) #Exponentiation
    >>> np.sqrt(b) #Square root
    >>> np.sin(a)  #Print sines of an array
    >>> np.cos(b) #Elementwise cosine
    >>> np.log(a)#Elementwise natural logarithm
    >>> e.dot(f) #Dot product 
    array([[7.,7.],[7.,7.]])

### Comparison:

    >>> a == b #Elementwise comparison

    array([[False , True, True],
                [ False,False ,False ]], dtype=bool)
    >>> a< 2 #Elementwise comparison
    array([True, False, False], dtype=bool)
    >>> np.array_equal(a, b) #Arraywise comparison

### Copying Arrays:

    >>>h = a.view()#Create a view of the array with the same data
    >>> np.copy(a) #Create a copy of the array
    >>>h = a.copy() #Create a deep copy of the array

### Sorting Arrays:

    >>> a.sort() #Sort an array
    >>> c.sort(axis=0) #Sort the elements of an array's axis

### Subsetting, Slicing, Indexing:

Subsetting::

    >>> a[2] #Select the element at the 2nd index
    3
    >>> b[1,2] #Select the element at row 1 column 2(equivalent to b[1][2])
    6.0

Slicing::

    >>> a[0:2]#Select items at index 0 and 1
    array([1, 2])
    >>> b[0:2,1] #Select items at rows 0 and 1 in column 1
    array([ 2.,5.])
    >>> b[:1] 
    #Select all items at row0(equivalent to b[0:1, :])
    array([[1.5, 2., 3.]])
    >>> c[1,...] #Same as[1,:,:]
    array([[[ 3., 2.,1.],[ 4.,5., 6.]]])
    >>> a[ : : -1] #Reversed array a array([3, 2, 1])

Boolean Indexing::

    >>> a[a<2] #Select elements from a less than 2
    array([1])

Fancy Indexing::

    >>> b[[1,0,1, 0],[0,1, 2, 0]] #Select elements(1,0),(0,1),(1,2) and(0,0)
    array([ 4. , 2. , 6. ,1.5])
    >>> b[[1,0,1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns
    array([[ 4. ,5. , 6. , 4.],[1.5, 2. , 3. ,1.5],[ 4. ,5. , 6. , 4.],[1.5, 2. , 3. ,1.5]])

### Array Manipulation:

Transposing Array::

    >>> i = np.transpose(b) #Permute array dimensions
    >>> i.T #Permute array dimensions

Changing Array Shape::

    >>> b.ravel() #Flatten the array
    >>> g.reshape(3, -2) #Reshape, but don’t change data  

Adding/Removing Elements::

    >>>h.resize((2,6)) #Return a new arraywith shape(2,6)
    >>> np.append(h,g) #Append items to an array
    >>> np.insert(a,1,5)  #Insert items in an array
    >>> np.delete(a,[1])  #Delete items from an array

Combining Arrays::

    >>> np.concatenate((a,d),axis=0) #Concatenate arrays
    array([1, 2, 3, 10, 15, 20])
    >>> np.vstack((a,b) #Stack arrays vertically(row wise)
    array([[1. , 2. , 3.],[1.5, 2. , 3.],[ 4. ,5. , 6. ]])
    >>> np.r_[e,f] #Stack arrays vertically(row wise)
    >>> np.hstack((e,f)) #Stack arrays horizontally(column wise)
    array([[7.,7.,1.,0.],[7.,7.,0.,1.]])
    >>> np.column_stack((a,d)) #Create stacked column wise arrays
    array([[1, 10],[ 2, 15],[ 3, 20]])
    >>> np.c_[a,d] #Create stacked column wise arrays

    
Splitting Arrays::

    >>> np.hsplit(a,3) #Split the array horizontally at the 3rd index
    [array([1]),array([2]),array([3])]
    >>> np.vsplit(c,2) #Split the array vertically at the 2nd index
    [array([[[ 1.5, 2. ,1.],[ 4. ,5. , 6. ]]]),
    array([[[ 3., 2., 3.],[ 4.,5., 6.]]])]

## <u>Pandas:</u>

    import pandas as pd

### Pandas Data Structures

Series::

    s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])

DataFrame::

    data = {'Country': ['Belgium',  'India',  'Brazil'],

    'Capital': ['Brussels',  'New Delhi',  'Brasilia'],

    'Population': [11190846, 1303171035, 207847528]} 

    df = pd.DataFrame(data,columns=['Country',  'Capital',  'Population'])

### I/O

Read and Write to CSV::

    pd.read_csv('file.csv', header=None, nrows=5)
    df.to_csv('myDataFrame.csv')

Read multiple sheets from the same file::

    xlsx = pd.ExcelFile('file.xls')
    df = pd.read_excel(xlsx,  'Sheet1')

Read and Write to Excel::

    pd.read_excel('file.xlsx')
    df.to_excel('dir/myDataFrame.xlsx',  sheet_name='Sheet1')

Read and Write to SQL Query or Database Table::

    from sqlalchemy import create_engine
    engine = create_engine('sqlite:///:memory:')
    pd.read_sql(SELECT * FROM my_table;, engine)
    pd.read_sql_table('my_table', engine)
    pd.read_sql_query(SELECT * FROM my_table;', engine)
    df.to_sql('myDf', engine)

### Selection

Get one element::

    s['b']
    -5

Get subset of a DataFrame::

    df[1:]
    Country     Capital   Population
    1  India    New Delhi 1303171035
    2  Brazil   Brasilia  207847528

By Position::

    df.iloc([0], [0])
    'Belgium'
    df.iat([0], [0])
    'Belgium'

By Label::

    df.loc([0],  ['Country'])
    'Belgium'
    df.at([0],  ['Country'])
    'Belgium'

By Label/Position::

    row::

    df.ix[2]
    Country      Brazil
    Capital    Brasilia
    Population  207847528

    columns::

    df.ix[:, 'Capital']
    0     Brussels
    1    New Delhi
    2     Brasilia

Select rows and columns::

    df.ix[1, 'Capital']
    'New Delhi'

Boolean Indexing::

    s[~(s > 1)]

Set index a of Series s to 6::

    s['a'] = 6

### Dropping

Drop values from rows (axis=0)::

    s.drop(['a',  'c'])

Drop values from columns(axis=1)::

    df.drop('Country', axis=1) 


### Retrieving Series/DataFrame Information

    df.shape
    df.index    
    df.columns
    df.info()
    df.count()

### Summary

    df.sum()
    df.cumsum()
    df.min()/df.max()
    df.idxmin()/df.idxmax() 
    df.describe()
    df.mean()
    df.median()

### Applying functions:

    f = lambda x: x*2
    df.apply(f)



    